// <auto-generated />
using LibraryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200208123328_AlteredSeedingData")]
    partial class AlteredSeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryManagement.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Department");

                    b.Property<string>("NameofAuthor");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 5,
                            NameofAuthor = "Mark Olami",
                            Title = "A-Z of Accounting"
                        },
                        new
                        {
                            Id = 2,
                            Department = 4,
                            NameofAuthor = "Frank   Ayaosi ",
                            Title = "Structures Engineering for beginners"
                        },
                        new
                        {
                            Id = 3,
                            Department = 2,
                            NameofAuthor = "Okundamiya Michael",
                            Title = "Circuit Theorem"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
